# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae3ae07cba0fde884d18007e0a8e2fabe8582badc8a1001f43f4496dd12ebfe8e13f9bdb73c24d2e91d6f80adaf51bc146e2dab1cfd2f62dfd159c328f51ec75

test:
  secret_key_base: 009bf7ea79c064322a00358fb07bff01fcf709065a478de0c49de1d4b01c93a8191d4f7bf38ceedcc70a171eabfb2080cbcec27ff2c286d119507d7c28467b8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
